REPOSITORY_LABELS = {
    1: "zenodo",
    2: "dryad",
    3: "uk-data-service",
    4: "syracuse-qualitative-data-repository",
    5: "dans",
    6: "dataverse-no",
    7: "ada",
    8: "sada",
    9: "hihsn",
    10: "harvard-dataverse",
    11: "finnish-social-science-data-archive",
    12: "aussda",
    13: "cessda",
    14: "databray",
    15: "icpsr",
    16: "open-data-uni-halle",
    17: "N/A",
    18: "harvard-murray-archive",
    19: "columbia-oral-history-archive",
    20: "sikt",
}
